services:
  - type: web
    name: bmw-dashboard
    runtime: python
    buildCommand: pip install --upgrade pip && pip install -r requirements.txt
    startCommand: gunicorn Dashboard:app.server
    envVars:
      - key: PYTHON_VERSION
        value: 3.10.13
